# Generated by Django 4.2.5 on 2023-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
