# Generated by Django 4.2.5 on 2023-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='bg_color',
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#ccffcc', max_length=10),
        ),
    ]
